### ISSUE TITLE
'download' command does not work

### ISSUE THREAD

**Issue by timukas** [MythicAgents/thanatos#15]
Hi,

Running latest Mythic with latest Thanatos.

'download' command does not download specified file.
'**No file id**' error is shown:

![image](https://github.com/MythicAgents/thanatos/assets/1915618/d5a8184a-3549-4415-a2c6-d2eeff6cc748)

Same file is successfully fetched with '**cat**' and '**shell cat**' commands.

P.s. Also noticed, that callback does not show process name:

![image](https://github.com/MythicAgents/thanatos/assets/1915618/56ccb9a1-d6e0-408d-a23c-8f51f25c1678)

**Comment by MEhrn00** [comment]
Mythic changed the format for download and upload messages. The changes break download/upload and the ssh download/upload commands. Will push fixes for those too.


I did not implement the routines for getting the current process name when performing the initial check in. I am currently in the process of rewriting the agent so I will add that in the rewrite.
