### ISSUE TITLE
Thanatos payload cannot connect to self-signed http service.

### ISSUE THREAD

**Issue by timukas** [MythicAgents/thanatos#16]
Hi,

Using latest Thanatos with latest Mythic.

Built default thanatos payload for Linux x64 with http profile. Http profile's ip address is basic Apache https redirector.
When starting payload, then i get following error:

```
thread 'main' panicked at src/profiles/mod.rs:117:49:
called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: InvalidData, error: InvalidCertificate(UnknownIssuer) })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

On https redirector i have self-signed certificate, with SAN records and CA:FALSE.

Other payloads medusa, poseidon and merlin work fine over same https redirector.

Sounds like a bug?

**Comment by MEhrn00** [comment]
The current HTTP library does not support self-signed TLS certificates https://github.com/MythicAgents/thanatos/issues/6#issuecomment-1110117393. Self-signed TLS certificate support will be added in the rewrite.
