### ISSUE TITLE
Windows Payload - Build Error

### ISSUE THREAD

**Issue by BerjawsM** [MythicAgents/thanatos#18]
Hello, 

When trying to build a Windows payload, I have the following error 

```         /usr/lib/gcc/x86_64-w64-mingw32/11.2.1/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/../lib/libws2_32.a(lib64_libws2_32_a-WspiapiLoad.o):(.text+0xe5): undefined reference to `__strcpy_chk'
          /usr/lib/gcc/x86_64-w64-mingw32/11.2.1/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/../lib/libws2_32.a(lib64_libws2_32_a-WspiapiLoad.o):(.text+0xfa): undefined reference to `__strcat_chk'
          /usr/lib/gcc/x86_64-w64-mingw32/11.2.1/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/../lib/libws2_32.a(lib64_libws2_32_a-WspiapiLoad.o):(.text+0x195): undefined reference to `__strcpy_chk'
          /usr/lib/gcc/x86_64-w64-mingw32/11.2.1/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/../lib/libws2_32.a(lib64_libws2_32_a-WspiapiLoad.o):(.text+0x1aa): undefined reference to `__strcat_chk'
          /usr/lib/gcc/x86_64-w64-mingw32/11.2.1/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/../lib/libws2_32.a(lib64_libws2_32_a-WspiapiLegacyGetNameInfo.o):(.text+0x24f): undefined reference to `__chk_fail'
          collect2: error: ld returned 1 exit status```

Here are the Build parameters used : 
![image](https://github.com/MythicAgents/thanatos/assets/12100046/de146fbb-9e38-4339-82b0-15cade997bd8)

**Comment by MEhrn00** [comment]
I think I know what the issue is. Going to test it and push the fix soon
