### ISSUE TITLE
Thanatos not starting

### ISSUE THREAD

**Issue by timukas** [MythicAgents/thanatos#19]
Installed latest thanatos on latest Mythic (on Linux x64) and got following errors:

![image](https://github.com/MythicAgents/thanatos/assets/1915618/691b0aa3-85c3-4b7f-8cb8-fad4f65c6532)

**Comment by MEhrn00** [comment]
Recent Mythic updates stopped bind mounting the agent runtime directory which was why the main.py file was not found. Just pushed some changes to include the runtime files inside the base container image which fixes this issue.
