### ISSUE TITLE
Disabled Reason: Agent doesn't support dynamic loading

### ISSUE THREAD

**Issue by gurubyte** [MythicAgents/thanatos#38]
I cant select which commands to include in agent. Actually, I cant to include even single command, its grayed out and says: "Disabled Reason: Agent doesn't support dynamic loading".
![ag1](https://github.com/MythicAgents/thanatos/assets/130367689/f2b62d32-93e3-4c95-838a-c18d5221e23b)
![ag12](https://github.com/MythicAgents/thanatos/assets/130367689/84b68d41-29a1-424b-9e48-851c9b4669f1)

I installed agent by classic way:

`sudo ./mythic-cli install github https://github.com/MythicAgents/thanatos`

and its ONLINE. I restarted Mythic server also but still unable to generate payload.

**Comment by its-a-feature** [comment]
So, if you look at that screenshot in the issue, all of the commands are listed on the side that says “commands included”, which means all of the commands are included in the agent at build time. The disabled piece means you can’t NOT include them because the agent doesn’t support dynamic loading

**Comment by gurubyte** [comment]
Oh, so they are already included. Sorry for my ignorance. Thanks so much for rapid response :)
