### ISSUE TITLE
[bug] upload command seems to fail on the mythic server side.

### ISSUE THREAD

**Issue by hulto** [MythicAgents/thanatos#9]
![image](https://user-images.githubusercontent.com/7121375/220743717-36286d71-e189-407e-8eaf-beb43d90a11b.png)

Tested on Linux and Windows same error for both.
Seems to be line 56, best guess the argument "path" doesn't exist.
![image](https://user-images.githubusercontent.com/7121375/220744011-113ae421-f677-4960-80a0-65222616e8e1.png)

Other commands seem to work as expected.

Running on an Ubuntu 22.04 server.
I setup the mythic server with the following commands:
```bash
apt update && apt install tmux vim docker.io docker-compose git
git clone https://github.com/its-a-feature/Mythic.git
cd Mythic
./mythic-cli install github https://github.com/MythicAgents/apfell
./mythic-cli install github https://github.com/MythicC2Profiles/http
./mythic-cli start
./mythic-cli install github https://github.com/MythicAgents/tetanus
./mythic-cli install github https://github.com/MythicAgents/freyja
```

**Comment by MEhrn00** [comment]
I see the issue. I'll try to have a fix either by the end of today or this weekend.

**Comment by MEhrn00** [comment]
Check if this fixes it. https://github.com/MythicAgents/tetanus/commit/de1d5b6c7c66859b32d7ce6f980066ec63e8952d
